version: '2'
services:
  web:
    build: .
    container_name: Dev
    environment:
      RAILS_ENV: development
    # command: bundle exec rails s --port 5000
    command: bundle exec rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
